name: testmate_example
description: Example usage of the TestMate package
version: 1.0.0

environment:
  sdk: ^3.6.1
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  testmate:
    path: ../
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0 