name: flutter_testmate
description: Testmate is a Flutter test utility package that provides a comprehensive suite of tools for testing and reporting Flutter applications.
version: 1.0.5
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1
  flutter: ">=3.32.4"

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  flutter_testmate:
